### ISSUE TITLE
Why am I getting this error?

### ISSUE THREAD

**Issue by Pantheon1** [MatteoGuadrini/mkpl#11] opened 2024-07-04 09:49 UTC
Traceback (most recent call last):
  File "f:\Python Folder\mkpl.py", line 36, in <module>
    from mutagen import File, MutagenError, id3
ModuleNotFoundError: No module named 'mutagen'
Thanks,
Pantheon

**Comment by MatteoGuadrini** [comment] 2024-07-04 20:28
Hi @Pantheon1,
`ModuleNotFoundError` is a python exception when the module is not found in the executed environment.
`mkpl` from version 1.7.0 (https://github.com/MatteoGuadrini/mkpl/releases/tag/v1.7.0), uses the `mutagen` package to identify ID3 tags, necessary for some features of the tool.

In your case, the problem is that you are running the module directly. This tool is not designed to work like this.
Please follow the [installation instructions](https://github.com/MatteoGuadrini/mkpl?tab=readme-ov-file#installation) and then run only from any folder:
`mkpl --help`

I'm closing this issue because it's not a problem with the tool but with Python itself.
See you soon!

**Closed by MatteoGuadrini** 2024-07-04 20:28 UTC
Labels: bug
